# Generated by Django 3.2.8 on 2021-12-19 19:50

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationLabelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.IntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'classification',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('job', models.IntegerField()),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.IntegerField()),
                ('category', models.SmallIntegerField(choices=[(0, 'Speech To Text'), (1, 'Document Classification')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('unit_qty', models.IntegerField()),
                ('truth_qty', models.IntegerField()),
                ('shared_qty', models.IntegerField()),
                ('min_qty', models.IntegerField()),
                ('accepted_qty', models.IntegerField(default=0)),
                ('unit_wage', models.IntegerField()),
                ('unit_bonus', models.IntegerField()),
                ('accept_threshold', models.IntegerField()),
                ('bonus_threshold', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truth_qty_ready', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('rank_category', models.SmallIntegerField(verbose_name=[(0, 'Requester'), (1, 'Annotator'), (2, 'Annotator Speech To Text'), (3, 'Annotator Document Classification')])),
                ('offset', models.IntegerField()),
            ],
            options={
                'db_table': 'rank',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.IntegerField()),
                ('rater', models.IntegerField()),
                ('ratee', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='SharedLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_unit', models.IntegerField()),
                ('task', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('label', models.CharField(default=None, max_length=1000, null=True)),
                ('accuracy', models.IntegerField()),
            ],
            options={
                'db_table': 'shared_label',
            },
        ),
        migrations.CreateModel(
            name='SharedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.IntegerField()),
                ('data', models.CharField(max_length=1000)),
                ('mean_value', models.CharField(default=None, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'shared_unit',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.IntegerField()),
                ('annotator', models.IntegerField()),
                ('unit_qty', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('shared_accuracy', models.IntegerField(default=0)),
                ('truth_accuracy', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TruthLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truth_unit', models.IntegerField()),
                ('task', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('label', models.CharField(default=None, max_length=1000, null=True)),
                ('accuracy', models.IntegerField()),
            ],
            options={
                'db_table': 'truth_label',
            },
        ),
        migrations.CreateModel(
            name='TruthUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.IntegerField()),
                ('data', models.CharField(max_length=1000)),
                ('label', models.CharField(default=None, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'truth_unit',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.IntegerField()),
                ('task', models.IntegerField(null=True)),
                ('data', models.CharField(max_length=1000)),
                ('label', models.CharField(max_length=1000, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('shared_id', models.IntegerField(default=None, null=True)),
                ('truth_id', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('password', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.SmallIntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Non Binary')])),
                ('year_of_birth', models.IntegerField()),
                ('role', models.SmallIntegerField(choices=[(0, 'Admin'), (1, 'Requester'), (2, 'Annotator')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('mean_accuracy', models.IntegerField(default=0)),
                ('label_c', models.IntegerField(default=0)),
                ('task_c', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
