# Generated by Django 3.2.8 on 2021-12-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mean_accuracy',
        ),
        migrations.AddField(
            model_name='user',
            name='mean_shared_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mean_truth_accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='shared_label_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='truth_label_c',
            field=models.IntegerField(default=0),
        ),
    ]
