# Generated by Django 3.2.8 on 2021-12-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211226_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
