# Generated by Django 3.2.8 on 2021-12-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='shared_accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='truth_accuracy',
            field=models.IntegerField(default=0),
        ),
    ]
