version: '3.8'

services:
  web:
    container_name: crolab_django
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    entrypoint: ["./entrypoint.sh"]
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    container_name: crolab_mysql
    image: mysql:8.0.21
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssword1"
      MYSQL_DATABASE: "crolab"
      MYSQL_USER: "crolab_dev"
      MYSQL_PASSWORD: "P@ssword1"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
  nginx:
    container_name: crolab_nginx
    build: ./nginx
    ports:
      - 1109:80
    depends_on:
      - web
